services:
    tello_suite:
        image: tello_suite:latest
        container_name: tello_suite
        build:
            context: .
        environment:
            - DISPLAY=${DISPLAY}
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix
        network_mode: "host"
        tty: true
        stdin_open: true
        command: "ros2 launch tello_bringup system_launch.py"
