site_name: Tello Suite
site_url: https://snt-arg.github.io/tello_suite/
repo_url: https://github.com/snt-arg/tello_suite
repo_name: snt-arg/tello_suite
theme:
  icon:
    repo: fontawesome/brands/github
  name: material
  palette: 
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

    # Light Mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
