landmark_detector_node:
    ros__parameters:
        standalone: false
        tick_rate: 30 # Hz
        img_input_topic: "/camera/image_raw"
        landmarks_topic: "/hand/landmarks"
        num_hands: 4
        min_detection_confidence: 0.5
        min_tracking_confidence: 0.5

landmark_annotator_node:
    ros__parameters:
        img_input_topic: "/camera/image_raw"
        landmarks_topic: "/hand/landmarks"
        annotated_img_topic: "/hand/annotated/image"

tello_driver:
    ros__parameters:
        # Settings
        alt_limit: 3 #[meters] Altitude limit (default: 30m)
        fast_mode: false
        video_mode: "4:3" # Valid options are "4:3" (wider view) or "16:9" (better quality)
        camera_exposure: 1 # Valid values: 0, 1, 2
        image_size: "640x480"

bt_server:
    ros__parameters:
        bt_name: person_tracking_bt #default_bt
        tick_freq: 60 # Hz
        stop_on_failure: false # Whether it should stop the tree from executing if the root fails.
