name: Foxy CI

on:
  push:
    branches:
      - main 
  pull_request:
    branches: [ "main" ]


jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:focal
    steps:
      - name: Setup ROS2
        uses: ros-tooling/setup-ros@v0.7
        with:
          # use-ros2-testing: true
          required-ros-distributions: foxy

      - name: Checkout Repository with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build ROS 2 package
        uses: ros-tooling/action-ros-ci@v0.3
        with:
          package-name: tello_app tello_bringup tello_bt tello_description tello_driver tello_msgs tello_nav # Add plugins too
          target-ros2-distro: foxy
